services:
  vue:
    image: ttmm_vue
    build: ./track-time-master-manager
    ports:
      - 8081:80
    networks:
      - ttmm_nw
  websockets:
    image: ttmm_ws
    build: ./websocket_server
networks:
  ttmm_nw:
    name: ttmm_network
    driver: bridge
